### PR TITLE
Ensure ticker item is on top of ticker so it ticks

### PR DESCRIPTION
**Pull request by cdubz**
Throw z-indexes at them!!! :hurtrealbad:

### CODE REVIEW

**Comment by overshard** [comment]
Aight, bet!

**Comment by cdubz** [comment]
It kinds of helps. There is still some other ticker items in there that make it unhappy. I have spent an unreasonable about of time watching the robot number go up 🤖 🤖 🤖 💯

**Comment by overshard** [comment]
Well if someone's spending time on it right now then that's a good sign! Dylan Lee is working on custom art, I'm trying to create the initial buildings and upgrades, wanting to add a resource and stock market system, also working on a story system of some kind. Still kind of in the figuring out what we want to do stage but having fun creating it.

**Comment by cdubz** [comment]
Yeah I'm always down for learning by making a game 👍 Y'all doing planning for this anywhere where I can lurk? 👀

**Comment by overshard** [comment]
Not really, kind of just playing it by ear at the start, will probably expand the README soon w/ ongoing plans, might make GitHub issues for things we want to do and discuss?

**Pull request merged**
